# Generated by Django 5.0.6 on 2024-05-19 04:58

import apps.person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('cpf', models.CharField(max_length=11, validators=[apps.person.models.validate_cpf])),
                ('birth_date', models.DateField(validators=[apps.person.models.validate_birth_date])),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('ideal_weight', models.FloatField()),
                ('situation', models.CharField(choices=[('abaixo_do_peso', 'Abaixo do Peso'), ('peso_ideal', 'Peso Ideal'), ('acima_do_peso', 'Acima do Peso')], max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
