# Generated by Django 5.0.6 on 2024-05-19 05:31

import apps.person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[apps.person.models.validate_cpf]),
        ),
    ]
